language: python

python:
  - 2.6
  - 2.7

branches:
  only:
    - develop

before_install:
  - pip install -q --use-mirrors Cython numpy

install:
  - pip install .

script: 
  - python setup.py test
