language: python

python:
  - 3.2
  - 3.1

branches:
  only:
    - develop
    - py-3
    - py-3-docs

before_install:
  - pip install -q --use-mirrors Cython numpy

install:
  - pip install .

script: 
  - python setup.py test

matrix:
  allow_failures:
    - python: 3.1
